# Generated by Django 5.2.1 on 2025-08-07 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elementos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elemento',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
