# Generated by Django 5.2.1 on 2025-10-30 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elemento',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='prestamo',
            name='elemento',
        ),
        migrations.CreateModel(
            name='PrestamoElemento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('elemento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prestamos.elemento')),
                ('prestamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_elementos', to='prestamos.prestamo')),
            ],
            options={
                'unique_together': {('prestamo', 'elemento')},
            },
        ),
        migrations.AddField(
            model_name='prestamo',
            name='elementos',
            field=models.ManyToManyField(related_name='prestamos', through='prestamos.PrestamoElemento', to='prestamos.elemento'),
        ),
    ]
